### ISSUE TITLE
mimic tag support

### ISSUE THREAD

**Issue by davetcoleman** [ros/robot_state_publisher#1]
Mimic tag support has been added to [URDF/JointModel](http://www.ros.org/wiki/urdf/XML/joint), but currently it is not supported in robot_state_publisher. Similar functionality is provided in [joint_state_publisher](http://www.ros.org/wiki/joint_state_publisher) but this is a non-ideal hack. Support for the mimic tag has been added to MoveIt's RobotState, but this does not help when using for example the RobotModel Rviz plugin.

@isucan :)

**Comment by jonbinney** [comment]
+1
Looking at the list of commits in this repo, it appears that nobody has added new features to this package for a while. If someone does have time to implement this feature in a pull request here, I'll help test and re-release this package.

**Comment by gavanderhoorn** [comment]
(re-adding after accidental deletion)

+1

This would allow me to visualise some closed chains without writing a custom node for it.

**Comment by thomas-moulard** [comment]
+1

**Comment by isucan** [comment]
done here: https://github.com/ros/robot_state_publisher/commit/a3e8bee93c9b4db2551df4a84d7307077681a4a4

**Comment by mitchellwills** [comment]
is it possible to merge this back into hydro?

**Comment by fmessmer** [comment]
see #15
