### ISSUE TITLE
[Windows][melodic] add Windows build support

### ISSUE THREAD

**Issue by seanyen** [ros/robot_state_publisher#107]
This is an enhancement ticket for `robot_state_publisher`. I am using this ticket to track all the required work to bring up `robot_state_publisher` to be able to build on Windows/MSVC (which is verified in https://aka.ms/ros project). And hope the maintainers can take a look. Thanks!

- [x] update how compiler flags are added #104
- [x] update install destination in CMakeLists.txt #103

**Comment by seanyen** [comment]
@sloretz @clalancette

**Comment by clalancette** [comment]
I think this is now done, so I'll close this out.  If there is still something that needs to be done for this, feel free to either re-open this issue or just open a new PR.
