### ISSUE TITLE
Parameter tf_prefix does not work with ROS for Windows

### ISSUE THREAD

**Issue by RoseFlunder** [ros/robot_state_publisher#111]
When I use the robot_state_publisher on a ROS Melodic on Windows installation the tf_prefix parameter is not used.
On my ROS Melodic on Ubuntu 18.04. installation the tf_prefix is used as expected by the robot_state_publisher.

Because I needed to make my ROS package compatible for both systems, I had to use an ugly workaround where replaced my URDF file with a XACRO file which I gave the tf_prefix to prepend it to all joint and link names.

Can you reproduce this behaviour and is it fixable?

**Comment by sloretz** [comment]
I'm surprised the behavior is different, but more to the point I don't think there is a path towards `tf_prefix` working on Windows. `tf_prefix` was dropped upstream in `tf2` ([see migration guide](http://wiki.ros.org/tf2/Migration#Removal_of_support_for_tf_prefix)). This repo removed the last mention of it in #82.

I'm not sure what the right solution for your use case is, but I'd recommend asking the question on https://answers.ros.org with more info about your use case (two robots sharing tf frames, or a urdf used multiple times in one robot, or something else). I'll close this for now. When you do open the question, please post a link here so others find it if they come across this issue first.
