### ISSUE TITLE
ROS 2: switch the license back to BSD

### ISSUE THREAD

**Issue by clalancette** [ros/robot_state_publisher#120]
The original ROS 2 port of this package switched the license to Apache 2.0, but it is clearly derived from the original ROS port which is under the BSD license.  Thus, the license on the ROS 2 port should be switched back to BSD.  Looking at the contributor list, it is largely OSRF people who contributed, but there are a few external contributors:

@pohzhiee
@pbeeson
@crdelsey
@bponsler

Could you reply here and tell us if you are OK with us relicensing your original contributions back to BSD?  Thanks in advance.

**Comment by bponsler** [comment]
I have no objections

**Comment by pohzhiee** [comment]
No objections
________________________________

**Comment by ghost** [comment]
I have no objections either.

**Comment by pbeeson** [comment]
No objections from me

**Comment by clalancette** [comment]
Thanks so much for prompt responses!  I'll open a PR changing this back to BSD shortly.

**Comment by clalancette** [comment]
Hm, not sure why github didn't auto-close this, but now that I've merged #121, this can be closed.  Thanks again everyone!
