### ISSUE TITLE
Why is there a leading slash?

### ISSUE THREAD

**Issue by maxlein** [ros/robot_state_publisher#128]
When starting robot state publisher with my urdf or also with the[ MARA robot ](https://github.com/AcutronicRobotics/MARA/blob/dashing/mara_description/urdf/mara_robot.urdf) one, I always have a leading slash in my frames.  
Whereas when publishing dynamic transforms via tf publishers I don't have them.  

 ```
ros2 run tf2_ros tf2_monitor 

RESULTS: for all Frames

Frames:
Frame: /base_link, published by <no authority available>, Average Delay: 0.0310374, Max Delay: 0.337976
Frame: /base_robot, published by <no authority available>, Average Delay: 0.0310414, Max Delay: 0.337976
Frame: /ee_link, published by <no authority available>, Average Delay: 0.0310442, Max Delay: 0.337978
Frame: /motor1_cover, published by <no authority available>, Average Delay: 0.0310411, Max Delay: 0.337976
Frame: /motor3_cover, published by <no authority available>, Average Delay: 0.0310387, Max Delay: 0.337975
Frame: /motor5_cover, published by <no authority available>, Average Delay: 0.0310388, Max Delay: 0.337977
Frame: /tool0, published by <no authority available>, Average Delay: 0.0310385, Max Delay: 0.337976

```  

I found this error through debugging [this ](https://github.com/ros2/geometry2/issues/219#event-2970010709) and [this error.](https://github.com/ros-planning/navigation2/issues/1458)

**Comment by clalancette** [comment]
It's essentially a leftover from the original port.  The slashes are removed in #126 .
