### ISSUE TITLE
Publishing tf with future timestamp if it's not static

### ISSUE THREAD

**Issue by weihunko** [ros/robot_state_publisher#131]
In `void RobotStatePublisher::publishFixedTransforms()`,  if the frame is not static, it will publish the tf with the timestamp that is 0.5 second ahead in the future.
--> https://github.com/ros/robot_state_publisher/blob/kinetic-devel/src/robot_state_publisher.cpp#L117

Can anyone elaborate the design decision behind this?

**Comment by wjwwood** [comment]
This sounds familiar, but I cannot remember the reason, @tfoote, @clalancette, or @sloretz, do you remember why this happens?

**Comment by wjwwood** [comment]
Maybe this? https://answers.ros.org/question/218864/why-does-amcl-post-date-tf-transform_tolerance/

**Comment by wjwwood** [comment]
Ah, it's mentioned here on the wiki:

https://wiki.ros.org/robot_state_publisher

> Note: All fixed transforms are future dated by 0.5s. 

which links to https://wiki.ros.org/tf/FAQ#Why_do_I_see_negative_average_delay_in_tf_monitor.3F
