### ISSUE TITLE
Create a new release of robot_state_publisher

### ISSUE THREAD

**Issue by mgrrx** [ros/robot_state_publisher#133]
There are a few commits on melodic-devel which were merged quite some time ago. In particular we at Magazino pulled in https://github.com/ros/robot_state_publisher/commit/50f135253d92633ba7657f667c6ab37a6f83b731 to link to the library in a different package.

Is there anything that speaks against a new release of this package?

**Comment by clalancette** [comment]
No particular reason, no.  It just hasn't been on my radar.  Thanks for the poke, I've done a release and opened https://github.com/ros/rosdistro/pull/24336.

**Comment by mgrrx** [comment]
awesome, thanks!
