### ISSUE TITLE
Catch Exception when parsing invalid urdf

### ISSUE THREAD

**Issue by mganglb** [ros/robot_state_publisher#140]
Hello, 
Imo it would be a great improvement to catch the thrown exception from `setupURDF(new_urdf)`. Atm the Ros node just dies if an invalid robot_description get loaded (on startup/or by an client). Especially if the robot_description is loaded via an client this is at least for me an unwanted behavior. 

In my fork I just added those lines, what fulfill my needs.

```
      std::string new_urdf = parameter.as_string();

      if (new_urdf.empty()) {
        result.successful = false;
        result.reason = "Empty URDF is not allowed";
        RCLCPP_INFO(get_logger(), "Empty URDF is not allowed");
        break;
      }

      try {
        setupURDF(new_urdf);
      }
      catch (std::runtime_error &exc) {
        RCLCPP_WARN(get_logger(), "Error parsing URDF");
        RCLCPP_WARN(get_logger(), exc.what());
        result.successful = false;
        result.reason = exc.what();
        break;
        }
      RCLCPP_INFO(get_logger(), "URDF OK");
```

regards mgangl

**Comment by clalancette** [comment]
robot_state_publisher crashing on startup with an invalid URDF is actually a desired feature.  It can't do any useful work without a URDF that is provided, so we want to inform the user of that as soon as possible.

However, I agree with you that when it changes during a `set_parameter`, it shouldn't crash.  See https://github.com/ros/robot_state_publisher/pull/141 for a fix.

**Comment by clalancette** [comment]
This was fixed long ago, so closing this out.
