### ISSUE TITLE
log4cxx missing

### ISSUE THREAD

**Issue by peter-lehner** [ros/robot_state_publisher#16]
I am compiling ROS Hydro desktop for my operating system with catkin.

When I attempt to compile robot_state_publisher I get the following error:

```
ld: cannot find -llog4cxx
```

In the CMakeLists.txt file the log4cxx library is simply added to target_link_libraries without searching for it:

```
target_link_libraries(${PROJECT_NAME} ${PROJECT_NAME}_solver log4cxx ${orocos_kdl_LIBRARIES})
```

I have compiled the log4cxx library for my operating system. How do you pick up the right binary during compilation? Is there any way of making this cross plattform, for example by using the package config file log4cxx supplies during compilation?

**Comment by lorenzoriano** [comment]
I have the same problem building on Mac OS with log4cxx brewed in

**Comment by peter-lehner** [comment]
To resolve this issue I simply removed the log4cxx dependency from the CMakeLists.txt. The robot state publisher was able to build and run without it, so I guessed it was a legacy dependancy.

**Comment by sloretz** [comment]
Closing this since Hydro is End-Of-Life and more recent branches do not have the log4cxx dependency.
