### ISSUE TITLE
[ros2] Sometimes node exits with exit code -6 after receiving a SIGINT

### ISSUE THREAD

**Issue by caioaamaral** [ros/robot_state_publisher#160]
One of my launch_tests sometimes catches `robot_state_publisher` exiting with code -6, IIUC it is a [SIGABRT](https://dsa.cs.tsinghua.edu.cn/oj/static/unix_signal.html).
<details>
<summary>Log</summary>

```console
  1: [INFO] [robot_state_publisher-1]: sending signal 'SIGINT' to process[robot_state_publisher-1]
  1: [robot_state_publisher-1] [INFO] [1617676615.709093956] [rclcpp]: signal_handler(signal_value=2)
  1: [robot_state_publisher-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  1: [robot_state_publisher-1]   what():  Couldn't initialize rcl timer handle: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/guard_condition.c:67
  Error: OR] [robot_state_publisher-1]: process has died [pid 11967, exit code -6, cmd '/opt/ros/foxy/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=robot_state_publisher -r __ns:=/ns --params-file /tmp/launch_params_e9xa16pk'].
```
</details>

Is this related with rlcpp generating random errors when handling SIGINT (as stated here https://github.com/ros2/rclpy/issues/527#issuecomment-713640332), or is something else happening here?

**Comment by clalancette** [comment]
Long delay here, sorry about that.

This looks to be an issue in the core of ROS 2, probably somewhere in `rclcpp` or in `rcl` itself.  As this doesn't seem to be a problem with `robot_state_publisher` itself, I'm going to close this.  But if you are still experiencing issues, I'll suggest opening a new issue on https://github.com/ros2/rclcpp .  Thanks.
