### ISSUE TITLE
Branch robot_state_publisher for Galactic

### ISSUE THREAD

**Issue by sloretz** [ros/robot_state_publisher#162]
@clalancette any objections?

This one seems easy: create a `galactic` branch from the `ros2` branch and update rosdistro to say `galactic` is the devel branch.

**Comment by clalancette** [comment]
Yes, it makes sense to me, since we've done it for all other releases.

**Comment by sloretz** [comment]
Branch exists, closing https://github.com/ros/robot_state_publisher/tree/galactic
