### ISSUE TITLE
[ros2] create duplicate nodes

### ISSUE THREAD

**Issue by wep21** [ros/robot_state_publisher#163]
### How to reproduce
`ros2 launch robot_state_publisher rsp-launch-urdf-file.xml`
### result
```
❯ ros2 node list
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/robot_state_publisher
/robot_state_publisher
```

**Comment by clalancette** [comment]
I can't reproduce here.  If I just run `ros2 launch robot_state_publisher rsp-launch-urdf-file.xml`, I get exactly one robot_state_publisher node.  Are you sure you don't have another copy running somewhere on your machine or elsewhere on the network?

**Comment by wep21** [comment]
I'm sorry, that was a zombie process.
