### ISSUE TITLE
phantom links show up in rviz when using robot_model

### ISSUE THREAD

**Issue by griz1112** [ros/robot_state_publisher#164]
Doing some work with the zed ros wrapper and rviz. I noticed that there were links showing up that were not from the zed but from another robot I'm working on plus the zed links. So just to make sure it was not something I've done I reinstalled linux cuda the zed sdk and rebuilt the zed_wrapper. Started that up and also rviz2. To my suprise the links for the robot still showed up along with the zed links that should be there. Very strange. Spews a lot of errors from rviz like this Warning: Invalid frame ID "wheel_right" passed to canTransform argument source_frame - frame does not exist. This is on ubuntu 18.04 and foxy is built from source. No idea how it could persist after a complete reinstall of everything.

**Comment by clalancette** [comment]
This sounds like there is something else on your network publishing the tf frames.  If you change your ROS_DOMAIN_ID to something other than zero, does the problem go away?

Regardless, the correct place for questions like this is on https://answers.ros.org, which is our centralized Q&A place.  So I'm going to close this out for now.
