### ISSUE TITLE
Not working on Raspberry Pi

### ISSUE THREAD

**Issue by wurong98** [ros/robot_state_publisher#174]
When running  `rostopic echo /tf_static`, 
urdf is noetic-devel/test/pr2.urdf
a message of over a gigabyte was predicted in tcpros. that seems highly unlikely, so I'll assume protocol synchronization is lost.

**Comment by sloretz** [comment]
Would you be willing to post a minimal reproducible example? It doesn't seem like there's enough information here to either reproduce, or to say for sure that this is a problem in `robot_state_publsher`.

**Comment by wurong98** [comment]
This may be a bug in ros.
https://github.com/AutoxingTech/simple_publisher_crash
They also found the same problem。

**Comment by 13037639065** [comment]
This information is very useful, thank you

**Comment by kingsimba** [comment]
It's a confirmed bug of GCC on ARM64: https://github.com/ros/ros_comm/issues/2197
