### ISSUE TITLE
lookupTransform argument target_frame does not exist

### ISSUE THREAD

**Issue by HaisenbergPeng** [ros/robot_state_publisher#185]
Hi, Guys! I was trying to get a transform from tf tree with code like this:
```  tf::TransformListener listener;

        tf::StampedTransform transformStamped_lidar_to_gps;
        try
        {
// tried ros::Time(0) as well
            listener.waitForTransform("lidar_link","gps", gpsMsg->header.stamp, ros::Duration(0.1));
            listener.lookupTransform("lidar_link", "gps", gpsMsg->header.stamp, transformStamped_lidar_to_gps);
        }
        catch (tf::TransformException &ex) 
        {
            ROS_ERROR("%s",ex.what());
            return;
        }
```
but ros gave me a error like this
```
[ERROR] [1639039113.143590487, 1521156875.186338832]: "lidar_link" passed to lookupTransform argument target_frame does not exist. 
```
I used "rosbag xxx --clock"  to publish "/clock", and set use_sim_time as true in launch file. rqt_tf_tree look like this:
![tf_tree](https://user-images.githubusercontent.com/72208396/145364156-e79503b6-fe84-4550-9702-aeb1c3f9d05b.jpg)

When I use "rosrun tf tf_echo lidar_link gps" to check the tf, it appears ok except the timestamp is exactly 0:
```
At time 0.000
- Translation: [-0.911, 0.358, -0.067]
- Rotation: in Quaternion [0.000, -0.061, 0.000, 0.998]
            in RPY (radian) [0.000, -0.122, 0.000]
            in RPY (degree) [0.000, -6.990, 0.000]

```
I have no idea where it goes wrong. Somebody help?

**Comment by clalancette** [comment]
For questions like this, please ask on https://answers.ros.org .  That is our central question-and-answer site, and someone should be able to help you there.  I'm going to close this out.
