### ISSUE TITLE
Static fixed transforms are not updated with robot_description parameter (Galactic Branch)

### ISSUE THREAD

**Issue by Patrick-Lascombe** [ros/robot_state_publisher#188]
This error occurs on the galactic branch, it has been fixed on the ROS2 branch with [this issue](https://github.com/ros/robot_state_publisher/issues/181). But it has yet to been fixed on the Galactic branch.

Is it planned to update the Galactic branch soon with this fix ?

**Comment by clalancette** [comment]
I'll go ahead and make a backport of that PR.

**Comment by clalancette** [comment]
See #189 for the backport.

**Comment by Patrick-Lascombe** [comment]
Works perfectly, thank you!
