### ISSUE TITLE
Rviz2 doesn't show point cloud because of wrong tf

### ISSUE THREAD

**Issue by lorenzo-bianchi** [ros/robot_state_publisher#194]
Hello everyone,
I am using ROS2 Foxy on Ubuntu 20.04 and I have a pan/tilt camera which publishes a point cloud I'd like to see on Rviz2.

[frames.pdf](https://github.com/ros/robot_state_publisher/files/8358564/frames.pdf)

As you can see in the previous pdf, there is a correct path from odom_frame (which I select on Rviz as Fixed Frame) to tilt_link, where chassis -> pan_link and pan_link -> tilt_link are normal tf, while all the other transformations are static.

When I add the point cloud on Rviz I have this message printed on terminal:

**[rviz]: Message Filter dropping message: frame 'tilt_link' at time 641.986 for reason 'Unknown'**

and it's like if Rviz can't find a proper transformation between those two frames.
Instead everything works correctly if I use only static transformations, so it's like if Rviz doesn't like "dynamic" tfs.

What does it depend on? 

Thank you very much for your help.

**Comment by clalancette** [comment]
For questions like this, please ask on https://answers.ros.org, which is our central question and answer site.  You are more likely to get an answer there, and the result will be easily searchable in the future.

I'm going to close this out for now.
