### ISSUE TITLE
undefined symbol error with ros2 run demo_nodes_cpp talker

### ISSUE THREAD

**Issue by Baldins** [ros/robot_state_publisher#196]
I get this error when running ros2 run demo_nodes_cpp talker

/opt/ros/foxy/lib/demo_nodes_cpp/talker: symbol lookup error: /opt/ros/foxy/lib/demo_nodes_cpp/talker: undefined symbol: _ZNK12class_loader11ClassLoader14getLibraryPathB5cxx11Ev

Is there anyone that can help me?

Thanks in advance!

**Comment by clalancette** [comment]
For questions like this, please use https://answers.ros.org, which is our centralized question and answer service.  You'll probably get better help there, and it will be more searchable in the future.

Closing this out for now.
