### ISSUE TITLE
CATKIN_MAKE ERROR 

### ISSUE THREAD

**Issue by saqihk** [ros/robot_state_publisher#217]
i have installed this package but when ran the command `catkin_make` it gave me an error while building

```
-- ~~  - robot_state_publisher (plain cmake)
-- ~~  - rviz_imu_plugin
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/aiot/ros_slam/build/CMakeFiles/CMakeOutput.log".
See also "/home/aiot/ros_slam/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
