### ISSUE TITLE
robot_state_publisher start Error

### ISSUE THREAD

**Issue by shufujian** [ros/robot_state_publisher#221]
just run `ros2 launch urdf_tutorial display.launch.py model:=urdf/01-myfirst.urdf`

![image](https://github.com/user-attachments/assets/37f45bfe-85b3-4dd1-a5f9-9fd709a79a89)

ROS distribution: humble

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
