### ISSUE TITLE
no public default constructor.

### ISSUE THREAD

**Issue by Karsten1987** [ros/robot_state_publisher#23]
is there any reason for not providing any public default constructor? This prevents any declaration of a robot state publisher as a member variable and initialize it on runtime.

**Comment by jackieokay** [comment]
No idea. I'll implement this for Kinetic.

**Comment by jackieokay** [comment]
:turtle:

**Comment by jackieokay** [comment]
hey @Karsten1987, if you're still interested in this feature, I made a potential implementation for the default constructor of `RobotStatePublisher` in #43. I can also add one for `JointStateListener`.

cheers!

**Comment by clalancette** [comment]
@Karsten1987 Are you still interested in this issue?  If so, we can probably pretty easily push it over the finish line.  If not, I'll close it out.  Just let me know.

**Comment by Karsten1987** [comment]
i like that once a year, we push that issue forward :D 

I am currently don't have any code which uses it, but I still think the proposal is valid.

**Comment by clalancette** [comment]
Haha, nice.  Sure, I'll leave it open, and hopefully get to it soon :).

**Comment by clalancette** [comment]
I'm going to close this out.  This is unlikely to ever be done for ROS 1, and the whole thing is rewritten in ROS 2.
