### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by rctoris** [ros/robot_state_publisher#27]
Just a friendly ping for a potential jade release to help some blocking packages for the upcoming beta.

**Comment by DLu** [comment]
Ioan -
Are you in a position where you can release this?
-David

**Comment by DLu** [comment]
I got an email from Ioan last week that said he could but doesn't have much time to do so, and he welcomes help. 

I've started tracing things up-stream: https://github.com/ros/robot_model/milestones/Jade%20Release

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/8125

**Comment by rctoris** [comment]
:+1: Thanks!

**Comment by mikepurvis** [comment]
(this bug can be closed)
