### ISSUE TITLE
TF static transforms for fixed joints

### ISSUE THREAD

**Issue by vooon** [ros/robot_state_publisher#33]
Hello,

Why this node do not use static TF for fixed joints?

**Comment by DLu** [comment]
Short answer: RSP predates static TF and is not as actively developed as it might need to be. Pull requests welcome.

**Comment by vooon** [comment]
So you think it is a good idea to port RSP to TF2? Also should i remove tf_prefix?

I can do this, but not sure when.

Also i tried to publish joints via static_transform_publisher, but rviz give warning on that joint.

**Comment by vooon** [comment]
Oh, it is already done by #28. But why it not merged yet?
