### ISSUE TITLE
API incompatibility in RobotStatePublisher::publishFixedTransforms

### ISSUE THREAD

**Issue by de-vri-es** [ros/robot_state_publisher#38]
Commit 8c27d2b09f43726340974e952ae646ba9601ca08 broke backwards compatibility of the C++ interface by adding a `bool use_tf_static` parameter to the `RobotStatePublisher::publishFixedTransforms` member function.

Adding a default value to either true or false will fix the incompatibility. If filling in a default is undesirable, we could add a deprecated overload that fills in the boolean value.

Either way, breaking the C++ API within a the same ROS release is a bit messy.

**Comment by scpeters** [comment]
I'm working on this
