### ISSUE TITLE
Mandatory dependency on rostest

### ISSUE THREAD

**Issue by jvgomez** [ros/robot_state_publisher#58]
Hi,

I have noticed that the dependency on rostest is always there. In other packages ([TF example](https://github.com/ros/geometry/blob/indigo-devel/tf/CMakeLists.txt#L51)) rostest is only find-packaged if `CATKIN_ENABLE_TESTING` is true. [Reference issue](https://github.com/ros/rosdistro/issues/3010)

I wonder whether there is a reason for not doing the same in this package.

**Comment by jvgomez** [comment]
Ping. I am interested on knowing the answer to know whether I should do a PR with the fix here (to indigo-devel) or to meta-ros with the corresponding patch.

**Comment by tfoote** [comment]
Moving the rostest dependency inside the conditional is better. You can then also move it to be a `test_depend` in the package.xml
