### ISSUE TITLE
Using equations as mimic multipliers

### ISSUE THREAD

**Issue by NickHornsey** [ros/robot_state_publisher#63]
Hello, 
I am currently working on a urdf and I want to create a mimic joint which moves in relation to the previous joint using the formula y=0.010x^2-0.540x+30.5 where y = the value of the mimic joint and x = the angle of the parent link. Is there a way to do this? 

Thank you

**Comment by DLu** [comment]
To my knowledge, that is not possible, it is only possible to do linear mimics.

**Comment by NickHornsey** [comment]
Thanks for getting back to me, do you know of any ways to work around this problem?

**Comment by skohlbr** [comment]
You could write your own little node that publishes the (slave) mimic joint's state based on the joint state of the master joint. That is probably the quickest solution, if not the most generic one.

**Comment by sloretz** [comment]
Hi @NickHornsey. I think http://answers.ros.org/questions/ would be a better place for this. Feel free to reopen.
