### ISSUE TITLE
Unintended actuator behavior

### ISSUE THREAD

**Issue by robotsorcerer** [ros/robot_state_publisher#68]
Hi,

 I have a robot description

   [Superchick](https://github.com/lakehanne/superchicko/blob/indigo-devel/superchick/superchick.xacro)

which includes a mannequin head and three actuators. Each actuator is supposed to control the each of three degree of freedoms of the head, i.e., (i) head vertically up, (ii) head and neck moving northwest, or (iii) head and neck moving northeast from the table top where the head lies in a supine position.

In my URDF model, I position one bladder directly under the head to control the pitch motion, position one left of neck-base and the last one right of neck base. I modeled the joints as [continuous joints](http://wiki.ros.org/urdf/XML/joint#attributes).

This is what I found though, when I run the model in rviz (by calling `roslaunch superchick display.launch`) I find that only the [right actuator](https://github.com/lakehanne/superchicko/blob/indigo-devel/superchick/superchick.xacro#L53-#L61)  controller exerts an effect on the head. When I comment out any other two controllers and roslaunch the urdf, I find that each of the actuators work as intended independent of the other actuators. The problem seems to be when I try to use them all simultaneously in rViz.

I tried to change the joint types to `floating` but the urdf parser seems to convert it to `"fixed"` every time spewing stuff like `joint type is unknown; joint x will be converted to fixed`

I am at a loss on what I could be missing.

Would appreciate any help or insight. 

Thanks!

**Comment by sloretz** [comment]
I think this would be better posted on http://answers.ros.org/questions/. There's another issue about ros/robot_model#188 related to `floating` joint not working. Feel free to reopen.
